[project]
authors = ["Niccolo Dejito <ncdejito@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "transformers_in_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "=24.4.0,<25"
